Add Button-chaser
Koch-Dustin/Button-chaser pull request #1
Opened 2022-10-24 07:05 UTC by Koch-Dustin

Changes:
   - Added Version1
   - Added Version2
   - Added Version3
   
PR:

2022-10-24 08:15 UTC, stefanluth requested changes

2022-10-24 08:15 UTC, stefanluth commented on Version3/index.js
> +  Distancex = horizontalDistanceFrom
Why do you remap this variable? :)

2022-10-24 08:15 UTC, stefanluth commented on Version3/index.js
> +      pushx = divBox.x + 10;
camelCase and don't forget to use `let` or `const` :)

2022-10-25 06:30 UTC, DevBastiS requested changes

2022-10-25 06:30 UTC, DevBastiS commented on Version1/index.html
> +    <head>
Indent in HTML files should always be 2 spaces. Please adjust your settings.

2022-10-25 06:30 UTC, DevBastiS commented on Version1/index.js
> +}
Always add a new line to the end of the file.

2022-10-25 06:30 UTC, DevBastiS commented on Version1/index.js
> +  if(distanceFromCenter(left, windowBox.left, buttonBox.width) < 0) {
Move this if conditions into speaking variables.

2022-10-25 06:30 UTC, DevBastiS commented on Version2/index.js
> +        button.style.left = "250px"
Weird indent here

2022-10-25 06:30 UTC, DevBastiS commented on Version2/index.js
> +    const x = e.pageX
Indent in js files should always be 2 spaces

2022-10-25 06:30 UTC, DevBastiS commented on Version2/index.js
> +    button_from_right = (horizontalDistanceFrom >= -145 && horizontalDistanceFrom <= -45) && (verticalDistanceFrom <= 20 && verticalDistanceFrom >= -25);
Use camelcase in JS. Also what does "buttom from right" mean?

2022-10-25 06:30 UTC, DevBastiS commented on Version2/style.css
> +*{
```suggestion
* {
```

2022-10-25 06:30 UTC, DevBastiS commented on Version2/style.css
> +    user-select: none;
Indent in CSS files should always be 2 spaces.

2022-10-25 06:30 UTC, DevBastiS commented on Version3/index.js
> +  if(divBox.x < -120) {
Move if condition to speaking variable.

2022-10-25 06:30 UTC, DevBastiS commented on Version3/index.js
> +  if(divBox.x < -120) {
Also what does 120 mean?

2022-11-07 07:48 UTC, DevBastiS requested changes

2022-11-07 07:48 UTC, DevBastiS commented on Version1/index.js
> +    setButtonPosition( buttonBox.x + horizontalOffset / horizontalDistanceFrom * 10, buttonBox.y + verticalOffset / verticalDistanceFrom * 10)
```suggestion
    setButtonPosition(buttonBox.x + horizontalOffset / horizontalDistanceFrom * 10, buttonBox.y + verticalOffset / verticalDistanceFrom * 10)
```

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +  const buttonBox = button.getBoundingClientRect();
```suggestion
  const buttonBox = button.getBoundingClientRect();
  
```

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +let button = document.getElementById("button");
```suggestion
let buttonToChase = document.getElementById("button");
```

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +  const horizontalDistanceFrom = distanceFromCenter(
```suggestion
  const horizontalDistanceFromButton = distanceFromCenter(
```

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +  const verticalDistanceFrom = distanceFromCenter(
```suggestion
  const verticalDistanceFromButton = distanceFromCenter(
```

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +  mouse_from_right =
```suggestion
  const mouseComesFromRightSide =
```

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +  mouse_from_left =
Same as above.

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +  mouse_from_top =
Same here

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +  mouse_from_bottom =
Same here

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +    console.log("Oben");
remove console logs.

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +  mouse_from_top_right =
Same here

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +  mouse_from_bottom_right =
Same here

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +  mouse_from_bottom_left =
Same here

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +  mouse_from_top_left =
You get the point ;)

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +  if (xborder <= 0 || xborder >= 1660) {
Move condition to speaking variable.

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +function set_button_position(left, top) {
```suggestion
function setButtonPosition(left, top) {
```

Sometimes you do it right, sometimes not.

2022-11-07 07:48 UTC, DevBastiS commented on Version2/index.js
> +function distanceFromCenter(boxPosition, mousePosition, boxSize) {
Here it is correct

2022-11-07 15:32 UTC, stefanluth requested changes

2022-11-07 15:32 UTC, stefanluth commented on Version1/index.js
> +  if(buttonHitsLeftEdge) {
```suggestion
  if (buttonHitsLeftEdge) {
```

And other occurrences :)

2022-11-07 15:32 UTC, stefanluth commented on Version1/index.js
> +  if(ButtonHitsUpperEdge) {
```suggestion
  if(buttonHitsUpperEdge) {
```

2022-11-09 08:21 UTC, DevBastiS requested changes

2022-11-09 08:21 UTC, DevBastiS commented on Version1/index.js
> +  }
```suggestion
  buttonHitsLeftEdge = distanceFromCenter(left, windowBox.left, buttonBox.width) < 0;
  buttonHitsRightEdge = distanceFromCenter(left, windowBox.right, buttonBox.width) > 0;
  buttonHitsUpperEdge = distanceFromCenter(top, windowBox.top, buttonBox.height) < 0;
  buttonHitsLowerEdge = distanceFromCenter(top, windowBox.bottom, buttonBox.height) > 0;
  buttonHitsAnyEdge = buttonHitsLeftEdge || buttonHitsRightEdge || buttonHitsUpperEdge || buttonHitsLowerEdge
  
  if (buttonHitsAnyEdge) {
    left = window.innerWidth / 2;
    top = window.innerHeight / 2;
    
    return;
  }
```

2022-11-09 08:21 UTC, DevBastiS commented on Version2/index.js
> +    buttonToChase.style.top = "70px";
Same refactoring possible as the one above.

2022-11-09 08:21 UTC, DevBastiS commented on Version3/index.js
> +  }
Same refactoring possible.

2022-11-10 12:11 UTC, stefanluth requested changes

2022-11-10 12:11 UTC, stefanluth commented on Version1/index.js
> +  const verticalDistanceFrom = distanceFromCenter(buttonBox.y, y, buttonBox.height)
distance from what? :D

2022-11-10 12:11 UTC, stefanluth commented on Version1/style.css
> +}
Two spaces indent :)

2022-11-10 12:11 UTC, stefanluth commented on Version2/index.js
> +    verticalDistanceFromButton >= -25;
The values seem arbitrary. Add variables :)

2022-11-12 17:18 UTC, stefanluth requested changes

2022-11-12 17:18 UTC, stefanluth commented on Version1/index.js
> +  mouseHitsVerticalTriggerpoint =
```suggestion
  const mouseHitsVerticalTriggerpoint =
```

2022-11-12 17:18 UTC, stefanluth commented on Version1/index.js
> +  buttonHitsAnyEdge =
Add `const`s

2022-11-12 17:18 UTC, stefanluth commented on Version1/index.js
> +function distanceFromCenter(boxPosition, mousePosition, boxSize) {
```suggestion
function getDistanceFromCenter(boxPosition, mousePosition, boxSize) {
```

or

```suggestion
function calculateDistanceFromCenter(boxPosition, mousePosition, boxSize) {
```

2022-11-12 17:18 UTC, stefanluth commented on Version2/index.js
> +top = buttonToChase.style.top;
`const`

2022-11-12 17:18 UTC, stefanluth commented on Version2/index.js
> +  const RideSideLowerBorderCoordinateValue = 20;
camelCase :)

2022-11-12 17:18 UTC, stefanluth commented on Version2/index.js
> +  const RideSideLowerBorderCoordinateValue = 20;
For the lines below as well. Or actually: You should declare constants like these at the beginning of the file, as `UPPER_CASE_CONSTANTS`.

2022-11-12 17:18 UTC, stefanluth commented on Version2/index.js
> +  ButtonHitsAnyEndOfTheBrowser =
`const`

2022-11-12 17:18 UTC, stefanluth commented on Version2/index.js
> +  top = top;
This doesn't do anything :)

2022-11-12 17:18 UTC, stefanluth commented on Version2/index.js
> +function distanceFromCenter(boxPosition, mousePosition, boxSize) {
add `get` or `calculate` to function name

2022-11-12 17:18 UTC, stefanluth commented on Version3/index.js
> +  buttonHitsAnyEdge = buttonHitsLeftEdge || buttonHitsRightEdge || buttonHitsUpperEdge || buttonHitsLowerEdge
`const`

2022-11-12 17:18 UTC, stefanluth commented on Version3/index.js
> +  if(buttonHitsAnyEdge) {
```suggestion
  if (buttonHitsAnyEdge) {
```

2022-11-14 07:15 UTC, DevBastiS requested changes

2022-11-14 07:15 UTC, DevBastiS commented on Version1/index.js
> +        (horizontalOffset / horizontalDistanceFromButtonCenter) * 10,
Add a new speaking variable for that.

2022-11-14 07:15 UTC, DevBastiS commented on Version1/index.js
> +      buttonBox.y + (verticalOffset / verticalDistanceFromButtonCenter) * 10
For this too, try to apply that you only use 1 allocation in 1 line of code.

2022-11-14 07:15 UTC, DevBastiS commented on Version2/index.js
> +  const LeftSideRightBorderCoordinateValue = 145;
Remove capital letters from variables.

2022-11-16 07:36 UTC, DevBastiS commented
Everything still open

2022-11-21 09:33 UTC, stefanluth requested changes
Remove .DS_Store :)

2022-11-21 09:33 UTC, stefanluth commented on Version2/index.js
> +let buttonToChase = document.getElementById("button");
This can be a `const` as well

2022-11-21 09:33 UTC, stefanluth commented on Version2/index.js
> +  let yborder = buttonToChase.getBoundingClientRect().y;
```suggestion
  const buttonBorderX = buttonToChase.getBoundingClientRect().x;
  const buttonBorderY = buttonToChase.getBoundingClientRect().y;
```

2022-11-21 09:33 UTC, stefanluth commented on Version2/index.js
> +}
👍 A text-book perfect function. Short and precise, no side effects, does what it says it should do. More of these :)

2022-11-21 14:16 UTC, DevBastiS approved these changes

2022-11-22 12:36 UTC, stefanluth approved these changes

2022-11-22 12:40 UTC, merged